language: go
#sudo: required

go:
    - 1.7
    - 1.6
    - 1.5
    - 1.4
    - tip

env:
    - ffmpeg=3.1.5
    - ffmpeg=3.2
    - ffmpeg=snapshot

matrix:
    fast_finish: true
    allow_failures:
        - go: tip
        - env: ffmpeg=snapshot

addons:
  apt:
    packages:
      - yasm
      - diffutils

# On develop branch
go_import_path: github.com/targodan/ffgopeg
# On master branch
#go_import_path: gopkg.in/targodan/ffgopeg.v1

before_install:
    - pushd $HOME
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/lib
    - export LIBRARY_PATH=$LIBRARY_PATH:$HOME/lib
    - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/lib/pkgconfig
    - curl https://ffmpeg.org/releases/ffmpeg-${ffmpeg}.tar.bz2 -o ffmpeg.tar.bz2
    - tar -vxf ffmpeg.tar.bz2
    - mkdir -p ffmpeg
    - mv ffmpeg-${ffmpeg}/* ffmpeg/ || true
    - cd ffmpeg/
    - ./configure --disable-programs --prefix=$HOME
    - make -j8
    - make install
    - popd

install:
    - go get -t -v ./...

script:
    - go build -v
    - go test -v -cover -race ./...
